// Resolve a public/ asset path against Vite's base ('./') so it works both in
// dev and in the static dist/ build dropped on any host.
export const asset = (p) => `${import.meta.env.BASE_URL}${p.replace(/^\/+/, '')}`

export const IMG = {
  egat: asset('images/about/EGAT.jpg'),
  mmth: asset('images/about/MMTH.jpg'),
  toa: asset('images/about/TOA.jpg'),
  huaykwang: asset('images/about/huaykwang.jpg'),
  panasonic: asset('images/about/panasonic.jpg'),
  somapaFifa: asset('images/about/somapa_fifa.jpg'),
  smtMachine: asset('images/about/SMT_Machine_01.jpg'),
  qcProcess: asset('images/about/QC_Process_01.jpg'),
  tisiCert: asset('images/about/TISI_certificate_1955-2551.jpg'),
  emergencyHero: asset('images/about/cover_hero.png'),
  ledSign: asset('images/led/led_sign.png'),
  fallDetection: asset('images/elderly-care/radar-fall-how.png'),
  trafficHero: asset('images/smart_traffic/slide01-hero.png'),
  maptaphutEmergency: asset('images/about/13_maptaphut_emergency.jpg'),
  smartlightScreen1: asset('images/smartlight/Screen1.webp'),
  smartPolePhoto: asset('images/smartlight/installation/IMG_5052.jpeg'),

  // CodeCube project photos (real screens, replace old slide placeholders)
  exatExpresswayMap: asset('images/about/codecube/project_exat_expressway_map.jpg'),
  exatTollgate: asset('images/about/codecube/project_exat_tollgate.jpg'),
  exatTrafficChart: asset('images/about/codecube/project_exat_traffic_chart.jpg'),
  ojaBigdataDashboard: asset('images/about/codecube/project_oja_bigdata_dashboard.jpg'),
  tescolotusClubcard: asset('images/about/codecube/project_tescolotus_clubcard.jpg'),
  tescolotusAppPromo: asset('images/about/codecube/project_tescolotus_app_promo.jpg'),
  gistdaThailandMap: asset('images/about/codecube/project_gistda_thailand_map.jpg'),
  dtacMydtacHero: asset('images/about/codecube/project_dtac_mydtac_hero.jpg'),
  truedigitalparkDashboardChart: asset('images/about/codecube/project_truedigitalpark_dashboard_chart.jpg'),
  healthDashboardDonuts: asset('images/about/codecube/project_health_dashboard_donuts.jpg'),
  yayoiDeliveryHero: asset('images/about/codecube/project_yayoi_delivery_hero.jpg'),
  mkMember: asset('images/about/codecube/project_mk_member.jpg'),
  indexInsurtechBanner: asset('images/about/codecube/project_index_insurtech_banner.jpg'),
  probationKioskWhite: asset('images/about/codecube/project_probation_kiosk_white.jpg'),
  cuteshopEcommerceMobile: asset('images/about/codecube/project_cuteshop_ecommerce_mobile.jpg'),
  keepqueCrmDashboard: asset('images/about/codecube/project_keepque_crm_dashboard.jpg'),
  fnWebsiteFranchise: asset('images/about/codecube/project_fn_website_franchise.jpg'),
  funplanetPartystar: asset('images/about/codecube/project_funplanet_partystar.jpg'),
  unadmeMarketingShowcase: asset('images/about/codecube/project_unadme_marketing_showcase.jpg'),

  codecubeLogo: asset('images/about/logos/codecube_logo.png'),
  gismoLion: asset('images/about/logos/gismo_lion.png'),
}

// Reference-customer logo wall — order is display order (priority names first).
export const CLIENT_LOGOS = [
  { name: 'การทางพิเศษแห่งประเทศไทย (EXAT)', src: asset('images/about/logos/client_exat.png') },
  { name: 'GISTDA', src: asset('images/about/logos/client_gistda.png') },
  { name: 'NT (โทรคมนาคมแห่งชาติ)', src: asset('images/about/logos/client_nt_national_telecom.png') },
  { name: 'CAT Telecom', src: asset('images/about/logos/client_cat_telecom.png') },
  { name: 'dtac', src: asset('images/about/logos/client_dtac.png') },
  { name: 'Tesco Lotus', src: asset('images/about/logos/client_tesco_lotus_app.png') },
  { name: 'MK Restaurants', src: asset('images/about/logos/client_mk_restaurants.png') },
  { name: 'Yayoi', src: asset('images/about/logos/client_yayoi.png') },
  { name: 'MCOT', src: asset('images/about/logos/client_mcot.png') },
  { name: 'กรมอนามัย', src: asset('images/about/logos/client_dept_of_health.png') },
  { name: 'กรมคุมประพฤติ', src: asset('images/about/logos/client_dept_of_probation.png') },
  { name: 'OJA', src: asset('images/about/logos/client_oja.png') },
  { name: 'True Digital Park', src: asset('images/about/logos/client_true_digital_park.png') },
  { name: 'Index Creative Village', src: asset('images/about/logos/client_index_creative_village.png') },
  { name: 'Amazon', src: asset('images/about/logos/client_amazon.png') },
  { name: 'Daily News', src: asset('images/about/logos/client_daily_news.png') },
  { name: 'OIC / CPB', src: asset('images/about/logos/client_oic_cpb.png') },
  { name: '555 Paper Plus', src: asset('images/about/logos/client_555_paperplus.png') },
  { name: 'Cute Shop', src: asset('images/about/logos/client_cute_shop.png') },
  { name: 'Family Amusement', src: asset('images/about/logos/client_family_amusement.png') },
  { name: 'FN (หนอมรอย)', src: asset('images/about/logos/client_fn_nomaroi.png') },
  { name: 'Fun Festa', src: asset('images/about/logos/client_fun_festa.png') },
  { name: 'Fun Planet', src: asset('images/about/logos/client_fun_planet.png') },
  { name: 'Tesco Lotus (คะแนนสะสม)', src: asset('images/about/logos/client_tesco_lotus.png') },
]

export const VID = {
  centralworld: asset('videos/centralworld_height.mp4'),
  centralworldPoster: asset('videos/centralworld_poster.jpg'),
  lpr: asset('videos/lpr-demo.mp4'),
  lprPoster: asset('videos/lpr-poster.jpg'),
  overheight: asset('videos/overheight_main.mp4'),
  overheightPoster: asset('videos/overheight_poster.jpg'),
  overheightScene: asset('videos/overheight_scene.mp4'),
  overheightScenePoster: asset('videos/overheight_scene_poster.jpg'),
  dashboard: asset('videos/0518.mp4'),
  dashboardPoster: asset('videos/0518_poster.jpg'),
  overheightDemo: asset('videos/overheight_demo.mp4'),
  overheightDemoPoster: asset('videos/overheight_demo_poster.jpg'),
  smtPcba: asset('videos/SMT_LED_PCBA_01.mp4'),
  smtPcbaPoster: asset('videos/SMT_LED_PCBA_01_poster.jpg'),
}
